parameters:
#    med_esperanza_principal.example.class: MedEsperanza\PrincipalBundle\Example

services:
#    med_esperanza_principal.example:
#        class: %med_esperanza_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
